/**
 * Gallery — per pipeline card render
 *
 * Tests that each of the 7 pipeline types (Recipes, Places, Media, Products,
 * Workouts, Tutorials, Home) renders a pipeline-type overlay on compact cards
 * and a chip row with the expected data fragment.  Also tests that clicking a
 * Recipes card expands it and renders the Ingredients group label.
 *
 * Translated from the Playwright Slice 7 spec (see 2026-04-20 Addendum in the
 * testing plan) to WebdriverIO + mocha.
 *
 * Key selector notes (verified against production code):
 *  - `.roost-pipeline-overlay[data-type="<type>"]`  — compact card overlay,
 *    rendered by renderPipelineOverlay() in pipeline-details.ts.  The
 *    data-type attribute was added alongside this spec.
 *  - `.roost-compact-chips`  — chip row below the cover, rendered in
 *    hydrateCard() via getCompactChips().  Added alongside this spec.
 *  - `.roost-pipeline-group-label`  — group header inside the expanded detail
 *    section, rendered by renderPipelineDetail().  Already in pipeline-details.ts.
 *
 * Chip values are derived from the synthetic fixture generated by
 * tests/fixtures/build-fixture-vault.mjs.  Expected fragments match the
 * first item in each category array (RECIPES[0], PLACES[0], etc.).
 */

import { browser } from "@wdio/globals";
import {
  applyGalleryCategoryFilter,
  scrollGalleryCardsIntoView,
} from "./gallery-e2e-helpers";

const PIPELINE_TIMEOUT = 15_000;

// Pipeline fixture table
// Chip fragments are derived from the synthetic fixture generated by
// node tests/fixtures/build-fixture-vault.mjs (see RECIPES[0], PLACES[0], etc.)
const PIPELINES: Array<{
  category: string;
  dataType: string;
  chipFragment: string;
}> = [
  // chipFragment = a value present on the FIRST card/row of each category in the
  // deterministic synthetic fixture. Recipes' first card is bm_1 (Middle Eastern).
  // Media is a watchables table (films/TV/books) — music like Spotify renders as an
  // embed elsewhere, not in this table — so we match a watchable (Netflix).
  { category: "Recipes",   dataType: "recipe",   chipFragment: "Middle Eastern" },
  { category: "Places",    dataType: "place",    chipFragment: "Rome"        },
  { category: "Media",     dataType: "media",    chipFragment: "Netflix"     },
  { category: "Products",  dataType: "product",  chipFragment: "Amazon"      },
  { category: "Workouts",  dataType: "workout",  chipFragment: "legs"        },
  { category: "Tutorials", dataType: "tutorial", chipFragment: "coffee"      },
  { category: "Home",      dataType: "home",     chipFragment: "mid-century" },
];

describe("Gallery — per pipeline card render", function () {
  // ── Shared setup: open Roost sidebar once before all tests ──
  before(async function () {
    // Open the Roost sidebar using the registered plugin command
    await browser.executeObsidianCommand("roost:open");

    // Wait for the sidebar React root to mount
    const sidebarEl = await $(".roost-root");
    await sidebarEl.waitForDisplayed({ timeout: 30_000 });

    // Give React time to render the library tree and sidebar panels
    await browser.pause(2000);

    // Wait for at least one category item to exist in the DOM
    const firstCategory = await $(`.tree-item-self[data-category="Recipes"]`);
    await firstCategory.waitForExist({ timeout: 15_000 });
  });

  it("clicking a Recipes card expands and shows Ingredients group", async function () {
    await applyGalleryCategoryFilter("Recipes");

    const recipeOverlay = await $('.roost-pipeline-overlay[data-type="recipe"]');
    await recipeOverlay.waitForDisplayed({ timeout: PIPELINE_TIMEOUT });

    const recipeCard = await $('.roost-card[data-roost-id="bm_0"]');
    await recipeCard.waitForDisplayed({ timeout: PIPELINE_TIMEOUT });
    await browser.execute((el) => (el as HTMLElement).click(), recipeCard);

    await browser.waitUntil(
      async () => (await $(".roost-card.roost-expanded")).isDisplayed(),
      { timeout: PIPELINE_TIMEOUT, timeoutMsg: "recipe card did not expand" },
    );

    const recipeSection = await $(
      '.roost-card.roost-expanded .roost-pipeline-section[data-pipeline-type="recipe"]',
    );
    await recipeSection.waitForDisplayed({
      timeout: PIPELINE_TIMEOUT,
      timeoutMsg: "recipe pipeline detail section not shown",
    });
    expect((await recipeSection.getText()).toLowerCase()).toContain("ingredients");
  });

  for (const { category, dataType, chipFragment } of PIPELINES) {
    it(`${category}: overlay[data-type="${dataType}"] and chips contain "${chipFragment}"`, async function () {
      await applyGalleryCategoryFilter(category);

      // Media uses a substitute table view instead of the card grid.
      if (category === "Media") {
        const table = await $(".roost-media-list-table");
        await table.waitForDisplayed({ timeout: PIPELINE_TIMEOUT });
        const tableText = await table.getText();
        expect(tableText.toLowerCase()).toContain(chipFragment.toLowerCase());
        return;
      }

      // Clicking the category calls plugin.openBookmarksBase() which opens the
      // gallery (BasesView).  First wait for any .roost-card to appear, which
      // confirms the gallery opened and Bases provided entries.  Then wait for
      // the specific pipeline overlay on a hydrated card.
      const anyCard = await $(".roost-card");
      await anyCard.waitForDisplayed({ timeout: PIPELINE_TIMEOUT });

      // Now wait for the pipeline overlay with the expected data-type attribute.
      const overlaySelector = `.roost-pipeline-overlay[data-type="${dataType}"]`;
      const overlayEl = await $(overlaySelector);
      await overlayEl.waitForDisplayed({ timeout: PIPELINE_TIMEOUT });

      // The compact chip row must contain the expected data fragment.
      // getCompactChips() builds: "cuisine · cookTime · Difficulty" for recipes,
      // "city, country" for places, etc.
      const chipsEl = await $(".roost-compact-chips");
      await chipsEl.waitForDisplayed({ timeout: PIPELINE_TIMEOUT });
      const chipsText = await chipsEl.getText();
      expect(chipsText.toLowerCase()).toContain(chipFragment.toLowerCase());
    });
  }
});
